name: Hello World Action
on: workflow_dispatch
# [push] # Triggers the workflow every time you push code

jobs:
# job name
  say-hello:
    runs-on: ubuntu-latest # github hosted runners
    steps:
      - name: manual dispatch
        run: echo "manual dispatched" # the command to execute
